language: cpp
compiler: gcc
dist: trusty
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq  gcc-5 g++-5 binutils zlib1g-dev libbz2-dev libsnappy-dev libjemalloc-dev libcurl4-openssl-dev libgflags-dev libmicrohttpd-dev
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5 --slave /usr/bin/gcov gcov /usr/bin/gcov-5
 - tar zxf <(curl -L https://github.com/facebook/zstd/archive/v1.2.0.tar.gz) && make -C zstd-* -j8 && sudo make -C zstd-* install && sudo ldconfig
script: make -j8 -C test/integration test
